"""Build/read the PNG metadata that fully describes how a plot was
produced, so a downloaded image can be exactly reproduced later.

Every PNG this project writes (from the UI or ``modforms.cli plot``)
embeds a ``modforms_reproduce`` text chunk: a JSON blob with the form's
own Fourier coefficients (not just a label -- so it doesn't depend on the
LMFDB being reachable or unchanged later), the region, the style and its
parameters, resolution, and background. ``modforms.cli replot`` reads it
back and re-renders from scratch.
"""

import json

from .coloring import custom_colormap
from .qexpansion import QExpansion

REPRODUCE_KEY = "modforms_reproduce"
SOFTWARE_TAG = "modforms (arXiv:2002.05234, Visualizing Modular Forms)"


def style_kwargs_to_json(style_kwargs, cmap_fingerprint=None):
    """A JSON-safe version of a style_kwargs dict: a custom colormap
    (built from a Colormap *object*, not directly JSON-serializable) is
    represented via ``cmap_fingerprint`` instead -- either a built-in
    colormap name (str) or ``("custom", (colors...), cyclic)``.
    """
    result = {k: v for k, v in style_kwargs.items() if k != "cmap"}
    if "cmap" in style_kwargs:
        if isinstance(cmap_fingerprint, tuple):
            result["cmap"] = {"type": "custom", "colors": list(cmap_fingerprint[1]), "cyclic": cmap_fingerprint[2]}
        else:
            result["cmap"] = {"type": "builtin", "name": cmap_fingerprint}
    return result


def build_metadata(
    form,
    source_kind,
    region,
    box,
    disk_extent,
    style,
    style_kwargs_json,
    content_shape,
    output_shape,
    target_ratio,
    background,
):
    """Build a dict of PNG text-chunk metadata (str -> str): a couple of
    conventional, human-readable PNG keywords, plus the full JSON
    reproduce payload under ``REPRODUCE_KEY``.
    """
    payload = {
        "schema": 1,
        "paper": "arXiv:2002.05234 (Lowry-Duda, Visualizing Modular Forms)",
        "project": "https://github.com/silasdiedrich/mod-forms",
        "form": {
            "source": source_kind,
            "label": getattr(form, "label", None),
            "weight": getattr(form, "weight", None),
            "level": getattr(form, "level", None),
            "start": form.start,
            "coeffs": [[float(c.real), float(c.imag)] for c in form.coeffs],
        },
        "region": region,
        "box": [list(box[0]), list(box[1])] if box is not None else None,
        "disk_extent": disk_extent,
        "style": style,
        "style_kwargs": style_kwargs_json,
        "content_shape": list(content_shape),
        "output_shape": list(output_shape),
        "target_ratio": target_ratio,
        "background": list(background),
    }
    reproduce_json = json.dumps(payload)

    label = payload["form"]["label"] or "custom form"
    description = f"{label} — {style} on the {region}"

    return {
        "Software": SOFTWARE_TAG,
        "Description": description,
        REPRODUCE_KEY: reproduce_json,
    }


def load_metadata(source):
    """Load the reproduce payload from a PNG path, file-like object, or an
    already-opened PIL Image.
    """
    from PIL import Image

    img = source if hasattr(source, "text") else Image.open(source)
    raw = getattr(img, "text", {}).get(REPRODUCE_KEY)
    if raw is None:
        raise ValueError(
            f"no {REPRODUCE_KEY!r} metadata found -- was this PNG generated by "
            f"modforms (the app, or `python -m modforms.cli plot`)?"
        )
    return json.loads(raw)


def form_from_metadata(meta):
    """Reconstruct the exact QExpansion (same Fourier coefficients) a
    render used, from its reproduce payload.
    """
    f = meta["form"]
    coeffs = [complex(re, im) for re, im in f["coeffs"]]
    return QExpansion(coeffs, start=f["start"], weight=f.get("weight"), level=f.get("level"), label=f.get("label"))


def style_kwargs_from_metadata(meta):
    """The inverse of :func:`style_kwargs_to_json`: turns a JSON-safe
    style_kwargs dict back into one usable with
    ``modforms.coloring``/``modforms.plotting`` (rebuilding a custom
    colormap object where needed).
    """
    kwargs = dict(meta.get("style_kwargs", {}))
    cmap_info = kwargs.get("cmap")
    if isinstance(cmap_info, dict):
        if cmap_info["type"] == "custom":
            kwargs["cmap"] = custom_colormap(cmap_info["colors"], cyclic=cmap_info["cyclic"])
        else:
            kwargs["cmap"] = cmap_info["name"]
    return kwargs
